# Generated by Django 5.1.1 on 2024-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
