# Generated by Django 5.1.1 on 2024-10-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blacklist', models.ManyToManyField(related_name='diet_blacklist', to='cookapp.ingredient')),
            ],
        ),
    ]
