# Generated by Django 5.1.1 on 2024-10-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0004_diets'),
        ('cookapp', '0004_favoriterecipe'),
    ]

    operations = [
    ]
