# Generated by Django 4.2.11 on 2024-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0004_remove_recipe_ingredients_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='cookapp.ingredient'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
