# Generated by Django 4.2.11 on 2024-10-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0005_merge_0004_diets_0004_favoriterecipe'),
        ('cookapp', '0006_remove_recipe_ingredients_and_more'),
    ]

    operations = [
    ]
