# Generated by Django 5.1.1 on 2024-11-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0009_recipe_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
